/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CzWO5bE7Llj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Card } from "@/components/ui/card"

export function Component() {
  const [isDarkMode, setIsDarkMode] = useState(false)
  const toggleDarkMode = () => {
    setIsDarkMode(!isDarkMode)
  }
  return (
    <div className={`min-h-screen ${isDarkMode ? "bg-black text-white" : "bg-white text-black"}`}>
      <header className="flex items-center justify-between p-4">
        <div className="flex items-center gap-2 text-lg font-semibold">
          <span>WS</span>
          <Link href="#" className="font-medium" prefetch={false}>
            Work
          </Link>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="ghost" onClick={toggleDarkMode}>
            {isDarkMode ? "Light" : "Dark"}
          </Button>
        </div>
      </header>
      <main className="flex flex-col md:flex-row">
        <section className="flex flex-col items-center p-8 md:w-1/3">
          <Avatar className="w-32 h-32 mb-4">
            <AvatarImage src="/placeholder-user.jpg" alt="Wael Sahbani" />
            <AvatarFallback>WS</AvatarFallback>
          </Avatar>
          <h1 className="text-3xl font-bold">Hello! I'm Wael Sahbani</h1>
          <p className="mt-2 text-lg">
            <span className={`${isDarkMode ? "text-green-500" : "text-green-700"}`}>Web Developer</span> with over 5+
            years of experience in crafting dynamic and responsive websites.
          </p>
          <div className="flex gap-4 mt-4">
            <Button variant="outline" className="flex items-center gap-2">
              <LinkedinIcon className="w-5 h-5" />
            </Button>
            <Button variant="outline" className="flex items-center gap-2">
              <GitlabIcon className="w-5 h-5" />
            </Button>
            <Button variant={`${isDarkMode ? "default" : "primary"}`} className="flex items-center gap-2">
              LET'S TALK
            </Button>
          </div>
        </section>
        <section className="flex flex-col p-8 md:w-2/3">
          <div className="mb-8">
            <h2 className={`text-xl font-bold flex items-center gap-2 ${isDarkMode ? "text-white" : "text-black"}`}>
              <UserIcon className="w-5 h-5" />
              ABOUT ME
            </h2>
            <p className={`mt-2 ${isDarkMode ? "text-gray-300" : "text-gray-700"}`}>
              Since the beginning, I've been deeply passionate about computer science, starting with no-code tools back
              in 2018. This early fascination led me to teach myself how to code, and over the years, I've honed my
              skills across various programming languages and technologies.
            </p>
            <p className={`mt-2 ${isDarkMode ? "text-gray-300" : "text-gray-700"}`}>
              I've had the privilege of working in a web development company, and now, I'm eager to build innovative
              projects, automate tasks, and push the boundaries in Web & Mobile Development, Open Source, and
              Competitive Programming.
            </p>
            <div className="flex gap-2 mt-4">
              <Badge variant={`${isDarkMode ? "default" : "primary"}`}>29 yo.</Badge>
              <Badge variant={`${isDarkMode ? "default" : "primary"}`}>Web</Badge>
              <Badge variant={`${isDarkMode ? "default" : "primary"}`}>Front-end</Badge>
              <Badge variant={`${isDarkMode ? "default" : "primary"}`}>Back-end</Badge>
            </div>
          </div>
          <div className="mb-8">
            <h2 className={`text-xl font-bold flex items-center gap-2 ${isDarkMode ? "text-white" : "text-black"}`}>
              <CodeIcon className="w-5 h-5" />
              MY DAILY TECH
            </h2>
            <div className="flex gap-4 mt-4">
              <WorkflowIcon className="w-6 h-6" />
              <LaptopIcon className="w-6 h-6" />
              <CodepenIcon className="w-6 h-6" />
              <CodepenIcon className="w-6 h-6" />
              <WindIcon className="w-6 h-6" />
              <EclipseIcon className="w-6 h-6" />
            </div>
          </div>
          <div className="mb-8">
            <h2 className={`text-xl font-bold flex items-center gap-2 ${isDarkMode ? "text-white" : "text-black"}`}>
              <BriefcaseIcon className="w-5 h-5" />
              MY WORKS
            </h2>
            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              <Card className="relative">
                <img
                  src="/placeholder.svg"
                  alt="Project 1"
                  className="w-full h-full object-cover"
                  width="300"
                  height="200"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <div
                  className={`absolute bottom-0 left-0 p-4 ${
                    isDarkMode ? "bg-black bg-opacity-50" : "bg-gray-200 bg-opacity-50"
                  } w-full`}
                >
                  <h3 className={`text-lg font-semibold ${isDarkMode ? "text-white" : "text-black"}`}>WAEL SAHBANI</h3>
                </div>
              </Card>
              <Card className="relative">
                <img
                  src="/placeholder.svg"
                  alt="Project 2"
                  className="w-full h-full object-cover"
                  width="300"
                  height="200"
                  style={{ aspectRatio: "300/200", objectFit: "cover" }}
                />
                <div
                  className={`absolute bottom-0 left-0 p-4 ${
                    isDarkMode ? "bg-black bg-opacity-50" : "bg-gray-200 bg-opacity-50"
                  } w-full`}
                >
                  <h3 className={`text-lg font-semibold ${isDarkMode ? "text-white" : "text-black"}`}>
                    YOUR VISION, OUR FOCUS
                  </h3>
                  <Button variant="link" className={`${isDarkMode ? "text-white" : "text-black"} mt-2`}>
                    Explore more <ArrowRightIcon className="w-4 h-4 inline" />
                  </Button>
                </div>
              </Card>
            </div>
          </div>
          <div className="mb-8">
            <Badge
              variant={`${isDarkMode ? "default" : "primary"}`}
              className={`${isDarkMode ? "bg-green-500 text-black" : "bg-green-700 text-white"} p-2`}
            >
              Open for Work: Full time / Remote
            </Badge>
          </div>
          <div>
            <h2 className={`text-xl font-bold ${isDarkMode ? "text-white" : "text-black"}`}>
              Solutions for web design, development, and digital marketing.
            </h2>
            <p className={`mt-2 ${isDarkMode ? "text-gray-300" : "text-gray-700"}`}>
              A website is essential in today's digital landscape because it serves as the primary online presence for
              businesses, organizations, and individuals. It provides a platform to showcase products, services, and
              information to a global audience, enhancing visibility and credibility.
            </p>
          </div>
        </section>
      </main>
    </div>
  )
}

function ArrowRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function BriefcaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  )
}


function CodeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function CodepenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 22 8.5 22 15.5 12 22 2 15.5 2 8.5 12 2" />
      <line x1="12" x2="12" y1="22" y2="15.5" />
      <polyline points="22 8.5 12 15.5 2 8.5" />
      <polyline points="2 15.5 12 8.5 22 15.5" />
      <line x1="12" x2="12" y1="2" y2="8.5" />
    </svg>
  )
}


function EclipseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a7 7 0 1 0 10 10" />
    </svg>
  )
}


function GitlabIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 13.29-3.33-10a.42.42 0 0 0-.14-.18.38.38 0 0 0-.22-.11.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18l-2.26 6.67H8.32L6.1 3.26a.42.42 0 0 0-.1-.18.38.38 0 0 0-.26-.08.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18L2 13.29a.74.74 0 0 0 .27.83L12 21l9.69-6.88a.71.71 0 0 0 .31-.83Z" />
    </svg>
  )
}


function LaptopIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 16V7a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9m16 0H4m16 0 1.28 2.55a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45L4 16" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function WindIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.7 7.7a2.5 2.5 0 1 1 1.8 4.3H2" />
      <path d="M9.6 4.6A2 2 0 1 1 11 8H2" />
      <path d="M12.6 19.4A2 2 0 1 0 14 16H2" />
    </svg>
  )
}


function WorkflowIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="8" x="3" y="3" rx="2" />
      <path d="M7 11v4a2 2 0 0 0 2 2h4" />
      <rect width="8" height="8" x="13" y="13" rx="2" />
    </svg>
  )
}
